### ISSUE TITLE
Schema for the Project

### ISSUE THREAD

**Issue by sanjithpk** [osl-vvce/quiz-platform#5]
Quizzes | Questions|User|Game
------------ | -------------| -------------| -------------
ID|Question ID|ID|Game ID
Name|Quiz ID|Name|Status
Owner|First Question ID|Email|User ID
Quiz Details|Last Question ID||Question ID
Start Date|||Quiz ID
End Date|||Score
First Question ID|||
Last Question ID|||

**Comment by shreevari** [comment]
Maybe you could add the schema to a Schema.md file.

**Comment by sanjithpk** [comment]
Sure, I'll do it.

**Comment by sanjithpk** [comment]
Yeah, I've created one, refer #6
