### ISSUE TITLE
Create a node server

### ISSUE THREAD

**Issue by sanjithpk** [osl-vvce/quiz-platform#7]
Create a server using node.js.

**Comment by dantehemerson** [comment]
I would like to help with this.
The server should be in this same repository? if so, could you give me a basic folder structure?

**Comment by sanjithpk** [comment]
@dantehemerson thanks for taking interest.
The server has a separate repository call [quiz-platform-server](https://github.com/osl-vvce/quiz-platform-server). I'll create an issue over there.
